name: Build and deploy to Docker Hub

on: 
  push: 
    branches: 
      - main

jobs: 
  build-and-push: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Log in to docker hub
      uses: docker/login-action@v3
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_SECRET_TOKEN}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./DockerFile/Dockerfile.myapp
        push: true
        tags: ankitkrsh5595/reactapp:latest
    
    - name: verify Pushed Image
      run: docker pull ankitkrsh5595/reactapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_ADDR }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker pull ankitkrsh5595/reactapp:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker system prune -af  # Clean up unused images/containers
          sudo docker run -d --name web-app -p 5173:5173 ankitkrsh5595/reactapp:latest