name: Build and deploy to Docker Hub

on: 
  push: 
    branches: 
      - main

jobs: 
  build and push: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repo
      uses: actions/checkout@v2

    -name: Log in to docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_SECRET_TOKEN}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./DockerFile/Dockerfile.myapp
        push: true
        tags: ankitkrsh5595/reactapp:latest
    
    -name: verify Pushed Image
      run: docker pull ankitkrsh5595/reactapp:latest

